name: SCA - Dependência C#

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Instalar Snyk e snyk-to-sarif
        run: npm install -g snyk snyk-to-sarif

      - name: Autenticar Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Executar SCA Snyk Test
        run: |
            snyk test --all-projects --json > snyk-report.json
            snyk-to-sarif -i snyk-report.json -o snyk-report.sarif
            
      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: snyk-report.sarif
            github_token: ${{ secrets.GITHUB_TOKEN }}
