name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      -  name: Checkout code
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk \
            -t ghcr.io/zaproxy/zaproxy \
            zap-baseline.py \
            -t http://localhost:5090 \
            -r zap-report.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@26f96dfa697d78a254ebef8b491950b5c9a9c7c4 # v4.3.0
        with:
          name: zap-report
          path: zap-report.html
