name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Build and start application
        run: |
          dotnet build
          nohup dotnet run --urls http://0.0.0.0:5090 &
          sleep 10

      - name: Run OWASP ZAP Baseline Scan
        run: |
          chmod -R 777 $GITHUB_WORKSPACE
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy \
            zap-baseline.py \
            -t http://localhost:5090 \
            -r zap-report.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: zap-report
          path: zap-report.html
