name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk \
            -t ghcr.io/zaproxy/zaproxy \
            zap-baseline.py \
            -t http://localhost:5090 \
            -r zap-report.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: zap-report
          path: zap-report.html


