name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build and start application
        run: |
          dotnet build InvestmentAPI/InvestmentAPI.csproj
          nohup dotnet run --project InvestmentAPI/InvestmentAPI.csproj --urls http://0.0.0.0:5090 &
          sleep 30    # aguarda a API subir

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy \
            zap-baseline.py \
            -t http://localhost:5090 \
            -r /zap/wrk/zap-report.html \
            --fail-on error || true

      - name: List files for debug
        run: ls -la ${{ github.workspace }}

      - name: Upload ZAP Report as Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ${{ github.workspace }}/zap-report.html
